---
# This file needs a gather_facts directive. 
#
# run
# ansible-playbook gather_facts.yml
#
- name: gather_facts
  hosts: localhost 
  become: no
  connection: local
  tasks: 

  - name: all facts
    debug: 
      var: ansible_facts

  - name: one fact
    debug: 
      var: ansible_facts.kernel_version

  - name: persistence
    debug: 
      msg: "Enabling 'use fact cache' in Ansible Tower would copy all this to memcache."
