---
- hosts: all
  gather_facts: no
  become: no
  tasks: 

  # Add a task to display "{{ inventory_hostname }}"
  # test by running 
  #   ansible-playbook -i inventory-dynamic-inventory.sh inventory-dynamic.yml
